// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: v1/message.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MRpcService_Request_FullMethodName         = "/message.MRpcService/Request"
	MRpcService_RequestMultResp_FullMethodName = "/message.MRpcService/RequestMultResp"
	MRpcService_MultRequest_FullMethodName     = "/message.MRpcService/MultRequest"
	MRpcService_DuplexStream_FullMethodName    = "/message.MRpcService/DuplexStream"
)

// MRpcServiceClient is the client API for MRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MRpcServiceClient interface {
	Request(ctx context.Context, in *MRpcMessage, opts ...grpc.CallOption) (*MRpcMessageAck, error)
	RequestMultResp(ctx context.Context, in *MRpcMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MRpcMessageAck], error)
	MultRequest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MRpcMessage, MRpcMessageAck], error)
	DuplexStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MRpcMessage, MRpcMessageAck], error)
}

type mRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMRpcServiceClient(cc grpc.ClientConnInterface) MRpcServiceClient {
	return &mRpcServiceClient{cc}
}

func (c *mRpcServiceClient) Request(ctx context.Context, in *MRpcMessage, opts ...grpc.CallOption) (*MRpcMessageAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MRpcMessageAck)
	err := c.cc.Invoke(ctx, MRpcService_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mRpcServiceClient) RequestMultResp(ctx context.Context, in *MRpcMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MRpcMessageAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MRpcService_ServiceDesc.Streams[0], MRpcService_RequestMultResp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MRpcMessage, MRpcMessageAck]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MRpcService_RequestMultRespClient = grpc.ServerStreamingClient[MRpcMessageAck]

func (c *mRpcServiceClient) MultRequest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MRpcMessage, MRpcMessageAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MRpcService_ServiceDesc.Streams[1], MRpcService_MultRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MRpcMessage, MRpcMessageAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MRpcService_MultRequestClient = grpc.ClientStreamingClient[MRpcMessage, MRpcMessageAck]

func (c *mRpcServiceClient) DuplexStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MRpcMessage, MRpcMessageAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MRpcService_ServiceDesc.Streams[2], MRpcService_DuplexStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MRpcMessage, MRpcMessageAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MRpcService_DuplexStreamClient = grpc.BidiStreamingClient[MRpcMessage, MRpcMessageAck]

// MRpcServiceServer is the server API for MRpcService service.
// All implementations must embed UnimplementedMRpcServiceServer
// for forward compatibility.
type MRpcServiceServer interface {
	Request(context.Context, *MRpcMessage) (*MRpcMessageAck, error)
	RequestMultResp(*MRpcMessage, grpc.ServerStreamingServer[MRpcMessageAck]) error
	MultRequest(grpc.ClientStreamingServer[MRpcMessage, MRpcMessageAck]) error
	DuplexStream(grpc.BidiStreamingServer[MRpcMessage, MRpcMessageAck]) error
	mustEmbedUnimplementedMRpcServiceServer()
}

// UnimplementedMRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMRpcServiceServer struct{}

func (UnimplementedMRpcServiceServer) Request(context.Context, *MRpcMessage) (*MRpcMessageAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedMRpcServiceServer) RequestMultResp(*MRpcMessage, grpc.ServerStreamingServer[MRpcMessageAck]) error {
	return status.Error(codes.Unimplemented, "method RequestMultResp not implemented")
}
func (UnimplementedMRpcServiceServer) MultRequest(grpc.ClientStreamingServer[MRpcMessage, MRpcMessageAck]) error {
	return status.Error(codes.Unimplemented, "method MultRequest not implemented")
}
func (UnimplementedMRpcServiceServer) DuplexStream(grpc.BidiStreamingServer[MRpcMessage, MRpcMessageAck]) error {
	return status.Error(codes.Unimplemented, "method DuplexStream not implemented")
}
func (UnimplementedMRpcServiceServer) mustEmbedUnimplementedMRpcServiceServer() {}
func (UnimplementedMRpcServiceServer) testEmbeddedByValue()                     {}

// UnsafeMRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MRpcServiceServer will
// result in compilation errors.
type UnsafeMRpcServiceServer interface {
	mustEmbedUnimplementedMRpcServiceServer()
}

func RegisterMRpcServiceServer(s grpc.ServiceRegistrar, srv MRpcServiceServer) {
	// If the following call panics, it indicates UnimplementedMRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MRpcService_ServiceDesc, srv)
}

func _MRpcService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MRpcServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MRpcService_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MRpcServiceServer).Request(ctx, req.(*MRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MRpcService_RequestMultResp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MRpcMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MRpcServiceServer).RequestMultResp(m, &grpc.GenericServerStream[MRpcMessage, MRpcMessageAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MRpcService_RequestMultRespServer = grpc.ServerStreamingServer[MRpcMessageAck]

func _MRpcService_MultRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MRpcServiceServer).MultRequest(&grpc.GenericServerStream[MRpcMessage, MRpcMessageAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MRpcService_MultRequestServer = grpc.ClientStreamingServer[MRpcMessage, MRpcMessageAck]

func _MRpcService_DuplexStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MRpcServiceServer).DuplexStream(&grpc.GenericServerStream[MRpcMessage, MRpcMessageAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MRpcService_DuplexStreamServer = grpc.BidiStreamingServer[MRpcMessage, MRpcMessageAck]

// MRpcService_ServiceDesc is the grpc.ServiceDesc for MRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MRpcService",
	HandlerType: (*MRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _MRpcService_Request_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestMultResp",
			Handler:       _MRpcService_RequestMultResp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MultRequest",
			Handler:       _MRpcService_MultRequest_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DuplexStream",
			Handler:       _MRpcService_DuplexStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/message.proto",
}
