// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MRpcMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	MsgId         int32                  `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRpcMessage) Reset() {
	*x = MRpcMessage{}
	mi := &file_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRpcMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRpcMessage) ProtoMessage() {}

func (x *MRpcMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRpcMessage.ProtoReflect.Descriptor instead.
func (*MRpcMessage) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *MRpcMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MRpcMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MRpcMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MRpcMessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	AckMsgId      int32                  `protobuf:"varint,2,opt,name=ackMsgId,proto3" json:"ackMsgId,omitempty"`
	AckData       []byte                 `protobuf:"bytes,3,opt,name=ackData,proto3" json:"ackData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MRpcMessageAck) Reset() {
	*x = MRpcMessageAck{}
	mi := &file_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MRpcMessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRpcMessageAck) ProtoMessage() {}

func (x *MRpcMessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRpcMessageAck.ProtoReflect.Descriptor instead.
func (*MRpcMessageAck) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *MRpcMessageAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MRpcMessageAck) GetAckMsgId() int32 {
	if x != nil {
		return x.AckMsgId
	}
	return 0
}

func (x *MRpcMessageAck) GetAckData() []byte {
	if x != nil {
		return x.AckData
	}
	return nil
}

var File_v1_message_proto protoreflect.FileDescriptor

const file_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x10v1/message.proto\x12\amessage\"U\n" +
	"\vMRpcMessage\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x05R\x05msgId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"d\n" +
	"\x0eMRpcMessageAck\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\backMsgId\x18\x02 \x01(\x05R\backMsgId\x12\x18\n" +
	"\aackData\x18\x03 \x01(\fR\aackData2\x96\x02\n" +
	"\vMRpcService\x12:\n" +
	"\aRequest\x12\x14.message.MRpcMessage\x1a\x17.message.MRpcMessageAck\"\x00\x12D\n" +
	"\x0fRequestMultResp\x12\x14.message.MRpcMessage\x1a\x17.message.MRpcMessageAck\"\x000\x01\x12@\n" +
	"\vMultRequest\x12\x14.message.MRpcMessage\x1a\x17.message.MRpcMessageAck\"\x00(\x01\x12C\n" +
	"\fDuplexStream\x12\x14.message.MRpcMessage\x1a\x17.message.MRpcMessageAck\"\x00(\x010\x01B'Z%github.com/Aiven37/MRpc/message/v1;v1b\x06proto3"

var (
	file_v1_message_proto_rawDescOnce sync.Once
	file_v1_message_proto_rawDescData []byte
)

func file_v1_message_proto_rawDescGZIP() []byte {
	file_v1_message_proto_rawDescOnce.Do(func() {
		file_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)))
	})
	return file_v1_message_proto_rawDescData
}

var file_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_message_proto_goTypes = []any{
	(*MRpcMessage)(nil),    // 0: message.MRpcMessage
	(*MRpcMessageAck)(nil), // 1: message.MRpcMessageAck
}
var file_v1_message_proto_depIdxs = []int32{
	0, // 0: message.MRpcService.Request:input_type -> message.MRpcMessage
	0, // 1: message.MRpcService.RequestMultResp:input_type -> message.MRpcMessage
	0, // 2: message.MRpcService.MultRequest:input_type -> message.MRpcMessage
	0, // 3: message.MRpcService.DuplexStream:input_type -> message.MRpcMessage
	1, // 4: message.MRpcService.Request:output_type -> message.MRpcMessageAck
	1, // 5: message.MRpcService.RequestMultResp:output_type -> message.MRpcMessageAck
	1, // 6: message.MRpcService.MultRequest:output_type -> message.MRpcMessageAck
	1, // 7: message.MRpcService.DuplexStream:output_type -> message.MRpcMessageAck
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_message_proto_init() }
func file_v1_message_proto_init() {
	if File_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_message_proto_goTypes,
		DependencyIndexes: file_v1_message_proto_depIdxs,
		MessageInfos:      file_v1_message_proto_msgTypes,
	}.Build()
	File_v1_message_proto = out.File
	file_v1_message_proto_goTypes = nil
	file_v1_message_proto_depIdxs = nil
}
